### ISSUE TITLE
available on pypi

### ISSUE THREAD

**Issue by starkillerOG** [easink/aioheos#1]
@easink could you please make this aioheos library available through [pypi](https://pypi.org/)?
Then this library could be installed through pip3 easily.

It would be awesom if this could be made part of the general homeassistant code.
Would you consider making a pull request for homeassistant?

**Comment by dahlmo** [comment]
I second this @starkillerOG this would make it possible to use `hass.aioheos.media_player` with newer versions of Home Assistant. Hope you will consider doing this @easink so that the Aioheos Media Player still can be used when people start migrating to the newer versions of Home Assistant.

**Comment by easink** [comment]
small modded version is now in pypi, and hopefully heos will be part of Home Assistant upstream.
